//decks actions

const RECEIVE_DECKS ='RECEIVE_DECKS';
const ADD_DECK = 'ADD_DECK';
const REMOVE_DECK = 'REMOVE_DECK';
const INCREMENT_CORRECT_ANSWER = 'INCREMENT_CORRECT_ANSWER';
const RESET_CORRECT_ANSWERS = 'RESET_CORRECT_ANSWERS';
const INCREMENT_NUMBER_QUESTIONS = 'INCREMENT_NUMBER_QUESTIONS';

export {
	RECEIVE_DECKS,
	ADD_DECK,
	REMOVE_DECK,
	INCREMENT_CORRECT_ANSWER,
	RESET_CORRECT_ANSWERS,
	INCREMENT_NUMBER_QUESTIONS
};

//questions actions

const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
const ADD_QUESTION = 'ADD_QUESTION';
const ADD_NEW_QUESTION_DECK = 'ADD_NEW_QUESTION_DECK';
const REMOVE_DECK_QUESTIONS = 'REMOVE_DECK_QUESTIONS';

export {
	RECEIVE_QUESTIONS,
	ADD_QUESTION,
	ADD_NEW_QUESTION_DECK,
	REMOVE_DECK_QUESTIONS
};

//initialize dummy data

const INITIALIZE_DATA = 'INITIALIZE_DATA';

export { INITIALIZE_DATA };

